
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.NorthWind.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Alphabetical list of productsRepository
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
public partial class AlphabeticalListOfProductRepository : GenericRepository<AlphabeticalListOfProduct> , IAlphabeticalListOfProductRepository<AlphabeticalListOfProduct>
{
    public AlphabeticalListOfProductRepository(EFContext context, string safeCode)
        : base(context, safeCode)
    {
    }
    public AlphabeticalListOfProductRepository(EFContext context)
        : base(context)
    {
    }
	    public AlphabeticalListOfProduct GetAlphabeticalListOfProductByKey(int ProductId, string ProductName, bool Discontinued, string CategoryName)
    {
        return FirstOrDefault(p => p.ProductId==ProductId && p.ProductName==ProductName && p.Discontinued==Discontinued && p.CategoryName==CategoryName);
    }
	}
}


		// </auto-generated>