
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.NorthWind.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // InvoicesRepository
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
public partial class InvoiceRepository : GenericRepository<Invoice> , IInvoiceRepository<Invoice>
{
    public InvoiceRepository(EFContext context, string safeCode)
        : base(context, safeCode)
    {
    }
    public InvoiceRepository(EFContext context)
        : base(context)
    {
    }
	    public Invoice GetInvoiceByKey(string CustomerName, string Salesperson, int OrderId, string ShipperName, int ProductId, string ProductName, decimal UnitPrice, short Quantity, float Discount)
    {
        return FirstOrDefault(p => p.CustomerName==CustomerName && p.Salesperson==Salesperson && p.OrderId==OrderId && p.ShipperName==ShipperName && p.ProductId==ProductId && p.ProductName==ProductName && p.UnitPrice==UnitPrice && p.Quantity==Quantity && p.Discount==Discount);
    }
	}
}


		// </auto-generated>