
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.NorthWind.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Products by CategoryRepository
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
public partial class ProductsByCategoryRepository : GenericRepository<ProductsByCategory> , IProductsByCategoryRepository<ProductsByCategory>
{
    public ProductsByCategoryRepository(EFContext context, string safeCode)
        : base(context, safeCode)
    {
    }
    public ProductsByCategoryRepository(EFContext context)
        : base(context)
    {
    }
	    public ProductsByCategory GetProductsByCategoryByKey(string CategoryName, string ProductName, bool Discontinued)
    {
        return FirstOrDefault(p => p.CategoryName==CategoryName && p.ProductName==ProductName && p.Discontinued==Discontinued);
    }
	}
}


		// </auto-generated>