
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.NorthWind.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Product Sales for 1997Repository
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
public partial class ProductSalesFor1997Repository : GenericRepository<ProductSalesFor1997> , IProductSalesFor1997Repository<ProductSalesFor1997>
{
    public ProductSalesFor1997Repository(EFContext context, string safeCode)
        : base(context, safeCode)
    {
    }
    public ProductSalesFor1997Repository(EFContext context)
        : base(context)
    {
    }
	    public ProductSalesFor1997 GetProductSalesFor1997ByKey(string CategoryName, string ProductName)
    {
        return FirstOrDefault(p => p.CategoryName==CategoryName && p.ProductName==ProductName);
    }
	}
}


		// </auto-generated>