
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.NorthWind.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Sales by CategoryRepository
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
public partial class SalesByCategoryRepository : GenericRepository<SalesByCategory> , ISalesByCategoryRepository<SalesByCategory>
{
    public SalesByCategoryRepository(EFContext context, string safeCode)
        : base(context, safeCode)
    {
    }
    public SalesByCategoryRepository(EFContext context)
        : base(context)
    {
    }
	    public SalesByCategory GetSalesByCategoryByKey(int CategoryId, string CategoryName, string ProductName)
    {
        return FirstOrDefault(p => p.CategoryId==CategoryId && p.CategoryName==CategoryName && p.ProductName==ProductName);
    }
	}
}


		// </auto-generated>