
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.Dms.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.Dms.DataLayer.Domain;
    using Modules.Dms.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Document
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial  class DocumentConfiguration : IEntityTypeConfiguration<Document>
    {
    public void Configure(EntityTypeBuilder<Document> builder)
        {
            builder.ToTable("Document", "dbo");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Name).HasColumnType("nvarchar(200)").HasMaxLength(200);
            builder.Property(x => x.Path).HasColumnType("nvarchar(250)").HasMaxLength(250);
            builder.Property(x => x.UploadDate).HasColumnName(@"UploadDate").HasColumnType("datetime");
            builder.Property(x => x.UploadUserName).HasColumnType("nvarchar(50)").HasMaxLength(50);
            builder.Property(x => x.LastAccessedDate).HasColumnName(@"LastAccessedDate").HasColumnType("datetime");
            builder.Property(x => x.FileSize).HasColumnName(@"FileSize").HasColumnType("bigint");



//TODO: Deleted foreign key and relation mapping configuration rows from here


            InitializePartial();
        }
        partial void InitializePartial();
    }
  
}


		// </auto-generated>