
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.NorthWind.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Invoices
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial  class InvoiceConfiguration : IEntityTypeConfiguration<Invoice>
    {
    public void Configure(EntityTypeBuilder<Invoice> builder)
        {
            builder.ToTable("Invoices", "dbo");
            builder.HasKey(x => new { x.CustomerName, x.Salesperson, x.OrderId, x.ShipperName, x.ProductId, x.ProductName, x.UnitPrice, x.Quantity, x.Discount });

            builder.Property(x => x.ShipName).HasColumnType("nvarchar(40)").HasMaxLength(40);
            builder.Property(x => x.ShipAddress).HasColumnType("nvarchar(60)").HasMaxLength(60);
            builder.Property(x => x.ShipCity).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.ShipRegion).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.ShipPostalCode).HasColumnType("nvarchar(10)").HasMaxLength(10);
            builder.Property(x => x.ShipCountry).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.CustomerId).HasColumnType("nchar(5)").HasMaxLength(5);
            builder.Property(x => x.CustomerName).HasColumnType("nvarchar(40)").IsRequired().HasMaxLength(40).ValueGeneratedNever();
            builder.Property(x => x.Address).HasColumnType("nvarchar(60)").HasMaxLength(60);
            builder.Property(x => x.City).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.Region).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.PostalCode).HasColumnType("nvarchar(10)").HasMaxLength(10);
            builder.Property(x => x.Country).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.Salesperson).HasColumnType("nvarchar(31)").IsRequired().HasMaxLength(31).ValueGeneratedNever();
            builder.Property(x => x.OrderId).HasColumnName(@"OrderID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.OrderDate).HasColumnName(@"OrderDate").HasColumnType("datetime");
            builder.Property(x => x.RequiredDate).HasColumnName(@"RequiredDate").HasColumnType("datetime");
            builder.Property(x => x.ShippedDate).HasColumnName(@"ShippedDate").HasColumnType("datetime");
            builder.Property(x => x.ShipperName).HasColumnType("nvarchar(40)").IsRequired().HasMaxLength(40).ValueGeneratedNever();
            builder.Property(x => x.ProductId).HasColumnName(@"ProductID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProductName).HasColumnType("nvarchar(40)").IsRequired().HasMaxLength(40).ValueGeneratedNever();
            builder.Property(x => x.UnitPrice).HasColumnType("decimal(19,4)").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Quantity).HasColumnName(@"Quantity").HasColumnType("smallint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Discount).HasColumnName(@"Discount").HasColumnType("real").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ExtendedPrice).HasColumnType("decimal(19,4)");
            builder.Property(x => x.Freight).HasColumnType("decimal(19,4)");



//TODO: Deleted foreign key and relation mapping configuration rows from here


            InitializePartial();
        }
        partial void InitializePartial();
    }
  
}


		// </auto-generated>