// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Modules.NorthWind.DataLayer
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Data.Interfaces;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Suppliers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public partial  class SupplierConfiguration : IEntityTypeConfiguration<Supplier>
    {
    public void Configure(EntityTypeBuilder<Supplier> builder)
        {
            builder.ToTable("Suppliers", "dbo");
            builder.HasKey(x => x.SupplierId);

            builder.Property(x => x.SupplierId).HasColumnName(@"SupplierID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.CompanyName).HasColumnType("nvarchar(40)").IsRequired().HasMaxLength(40);
            builder.Property(x => x.ContactName).HasColumnType("nvarchar(30)").HasMaxLength(30);
            builder.Property(x => x.ContactTitle).HasColumnType("nvarchar(30)").HasMaxLength(30);
            builder.Property(x => x.Address).HasColumnType("nvarchar(60)").HasMaxLength(60);
            builder.Property(x => x.City).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.Region).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.PostalCode).HasColumnType("nvarchar(10)").HasMaxLength(10);
            builder.Property(x => x.Country).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.Phone).HasColumnType("nvarchar(24)").HasMaxLength(24);
            builder.Property(x => x.Fax).HasColumnType("nvarchar(24)").HasMaxLength(24);
            builder.Property(x => x.HomePage).HasColumnName(@"HomePage").HasColumnType("ntext").HasMaxLength(1073741823);



//TODO: Deleted foreign key and relation mapping configuration rows from here


            InitializePartial();
        }
        partial void InitializePartial();
    }
  
}
// </auto-generated>
