// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 2
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Modules.NorthWind.Configuration
{
    using Modules.NorthWind.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // Customers
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public  class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
    public void Configure(EntityTypeBuilder<Customer> builder)
        {
            builder.ToTable("Customers", "dbo");
            builder.HasKey(x => x.CustomerId);

            builder.Property(x => x.CustomerId).HasColumnType("nchar(5)").IsRequired().HasMaxLength(5).ValueGeneratedNever();
            builder.Property(x => x.CompanyName).HasColumnType("nvarchar(40)").IsRequired().HasMaxLength(40);
            builder.Property(x => x.ContactName).HasColumnType("nvarchar(30)").HasMaxLength(30);
            builder.Property(x => x.ContactTitle).HasColumnType("nvarchar(30)").HasMaxLength(30);
            builder.Property(x => x.Address).HasColumnType("nvarchar(60)").HasMaxLength(60);
            builder.Property(x => x.City).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.Region).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.PostalCode).HasColumnType("nvarchar(10)").HasMaxLength(10);
            builder.Property(x => x.Country).HasColumnType("nvarchar(15)").HasMaxLength(15);
            builder.Property(x => x.Phone).HasColumnType("nvarchar(24)").HasMaxLength(24);
            builder.Property(x => x.Fax).HasColumnType("nvarchar(24)").HasMaxLength(24);



//TODO: Deleted foreign key and relation mapping configuration rows from here


        }
    }
  
}
// </auto-generated>
