
// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
#pragma warning disable 1591    //  Ignore 'Missing XML Comment' warning


namespace Modules.NorthWind.DataLayer 
{
    using EFTemplateCore;
    using EFTemplateCore.Interfaces;
    using Modules.NorthWind.DataLayer.Data;
    using Modules.NorthWind.DataLayer.Domain;
    using Modules.NorthWind.DataLayer.Domain.Enums;
    using System.Data.Common;
	using Microsoft.EntityFrameworkCore;
	using Microsoft.EntityFrameworkCore.Metadata.Builders;
    // INorthWindUnitOfWork
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public interface INorthWindUnitOfWork  : System.IDisposable
    {
		AlphabeticalListOfProductRepository AlphabeticalListOfProductRepository { get; }
		CategoryRepository CategoryRepository { get; }
		CategorySalesFor1997Repository CategorySalesFor1997Repository { get; }
		CurrentProductListRepository CurrentProductListRepository { get; }
		CustomerRepository CustomerRepository { get; }
		CustomerAndSuppliersByCityRepository CustomerAndSuppliersByCityRepository { get; }
		CustomerDemographicRepository CustomerDemographicRepository { get; }
		EmployeeRepository EmployeeRepository { get; }
		InvoiceRepository InvoiceRepository { get; }
		OrderRepository OrderRepository { get; }
		OrderDetailRepository OrderDetailRepository { get; }
		OrderDetailsExtendedRepository OrderDetailsExtendedRepository { get; }
		OrdersQryRepository OrdersQryRepository { get; }
		OrderSubtotalRepository OrderSubtotalRepository { get; }
		ProductRepository ProductRepository { get; }
		ProductsAboveAveragePriceRepository ProductsAboveAveragePriceRepository { get; }
		ProductSalesFor1997Repository ProductSalesFor1997Repository { get; }
		ProductsByCategoryRepository ProductsByCategoryRepository { get; }
		QuarterlyOrderRepository QuarterlyOrderRepository { get; }
		RegionRepository RegionRepository { get; }
		SalesByCategoryRepository SalesByCategoryRepository { get; }
		SalesTotalsByAmountRepository SalesTotalsByAmountRepository { get; }
		ShipperRepository ShipperRepository { get; }
		SummaryOfSalesByQuarterRepository SummaryOfSalesByQuarterRepository { get; }
		SummaryOfSalesByYearRepository SummaryOfSalesByYearRepository { get; }
		SupplierRepository SupplierRepository { get; }
		TerritoryRepository TerritoryRepository { get; }
	}
}


		// </auto-generated>